create table if not exists public.people (
    person_id bigint generated by default as identity primary key,
    name text not null,
    notes text not null default '',
    face_thumbnail_base64 text,
    is_labeled boolean not null default false,
    created_at timestamptz not null default timezone('utc', now()),
    last_seen timestamptz not null default timezone('utc', now())
);

create table if not exists public.embeddings (
    embedding_id bigint generated by default as identity primary key,
    person_id bigint not null references public.people(person_id) on delete cascade,
    vector real[] not null,
    model_name text not null default 'edgeface_base',
    created_at timestamptz not null default timezone('utc', now()),
    constraint embeddings_vector_len check (cardinality(vector) = 512)
);

create index if not exists embeddings_person_id_idx on public.embeddings(person_id);

create table if not exists public.interactions (
    interaction_id bigint generated by default as identity primary key,
    person_id bigint references public.people(person_id) on delete set null,
    timestamp timestamptz not null default timezone('utc', now()),
    transcript text,
    context text
);

create index if not exists interactions_person_id_idx on public.interactions(person_id);
